### ISSUE TITLE
Is grunt-contrib-copy handling symlinks?

### ISSUE THREAD

**Issue by dominiksteiner** [BroadsoftLabs/hubGruntTasks#16]
If you do a 
```
bower link hub-lib
```
in any of the integrations and then lift them up they will get stucked in the grunt task at
```
verbose: Grunt :: Running "copy:dev" (copy) task
```
Is there any way of letting grunt-contrib-copy handle bower link too?

**Comment by dominiksteiner** [comment]
@jodonnell-broadsoft any ideas?

**Comment by jodonnell-broadsoft** [comment]
It looks like it does not support this. I would suggest you just merge your main branches into HubLib before you work on other branches. I don't think we need to do this but if you can find a way to do it, I'm all ears. grunt-symlink might be what you are looking for.
